/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// VideoStatusEncodingMetadata struct for VideoStatusEncodingMetadata
type VideoStatusEncodingMetadata struct {
	// The width of the video in pixels.
	Width *int32 `json:"width,omitempty"`
	// The height of the video in pixels.
	Height *int32 `json:"height,omitempty"`
	// The number of bits processed per second.
	Bitrate *float32 `json:"bitrate,omitempty"`
	// The length of the video.
	Duration *int32 `json:"duration,omitempty"`
	// The frequency with which consecutive images or frames appear on a display. Shown in this API as frames per second (fps).
	Framerate *int32 `json:"framerate,omitempty"`
	// How many samples per second a digital audio system uses to record an audio signal. The higher the rate, the higher the frequencies that can be recorded. They are presented in this API using hertz.
	Samplerate *int32 `json:"samplerate,omitempty"`
	// The method used to compress and decompress digital video. API Video supports all codecs in the libavcodec library.
	VideoCodec *string `json:"videoCodec,omitempty"`
	// The method used to compress and decompress digital audio for your video.
	AudioCodec  *string         `json:"audioCodec,omitempty"`
	AspectRatio *NullableString `json:"aspectRatio,omitempty"`
}

// NewVideoStatusEncodingMetadata instantiates a new VideoStatusEncodingMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoStatusEncodingMetadata() *VideoStatusEncodingMetadata {
	this := VideoStatusEncodingMetadata{}
	return &this
}

// NewVideoStatusEncodingMetadataWithDefaults instantiates a new VideoStatusEncodingMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoStatusEncodingMetadataWithDefaults() *VideoStatusEncodingMetadata {
	this := VideoStatusEncodingMetadata{}
	return &this
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *VideoStatusEncodingMetadata) GetWidth() int32 {
	if o == nil || o.Width == nil {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoStatusEncodingMetadata) GetWidthOk() (*int32, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *VideoStatusEncodingMetadata) SetWidth(v int32) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *VideoStatusEncodingMetadata) GetHeight() int32 {
	if o == nil || o.Height == nil {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoStatusEncodingMetadata) GetHeightOk() (*int32, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *VideoStatusEncodingMetadata) SetHeight(v int32) {
	o.Height = &v
}

// GetBitrate returns the Bitrate field value if set, zero value otherwise.
func (o *VideoStatusEncodingMetadata) GetBitrate() float32 {
	if o == nil || o.Bitrate == nil {
		var ret float32
		return ret
	}
	return *o.Bitrate
}

// GetBitrateOk returns a tuple with the Bitrate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoStatusEncodingMetadata) GetBitrateOk() (*float32, bool) {
	if o == nil || o.Bitrate == nil {
		return nil, false
	}
	return o.Bitrate, true
}

// HasBitrate returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasBitrate() bool {
	if o != nil && o.Bitrate != nil {
		return true
	}

	return false
}

// SetBitrate gets a reference to the given float32 and assigns it to the Bitrate field.
func (o *VideoStatusEncodingMetadata) SetBitrate(v float32) {
	o.Bitrate = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *VideoStatusEncodingMetadata) GetDuration() int32 {
	if o == nil || o.Duration == nil {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoStatusEncodingMetadata) GetDurationOk() (*int32, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *VideoStatusEncodingMetadata) SetDuration(v int32) {
	o.Duration = &v
}

// GetFramerate returns the Framerate field value if set, zero value otherwise.
func (o *VideoStatusEncodingMetadata) GetFramerate() int32 {
	if o == nil || o.Framerate == nil {
		var ret int32
		return ret
	}
	return *o.Framerate
}

// GetFramerateOk returns a tuple with the Framerate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoStatusEncodingMetadata) GetFramerateOk() (*int32, bool) {
	if o == nil || o.Framerate == nil {
		return nil, false
	}
	return o.Framerate, true
}

// HasFramerate returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasFramerate() bool {
	if o != nil && o.Framerate != nil {
		return true
	}

	return false
}

// SetFramerate gets a reference to the given int32 and assigns it to the Framerate field.
func (o *VideoStatusEncodingMetadata) SetFramerate(v int32) {
	o.Framerate = &v
}

// GetSamplerate returns the Samplerate field value if set, zero value otherwise.
func (o *VideoStatusEncodingMetadata) GetSamplerate() int32 {
	if o == nil || o.Samplerate == nil {
		var ret int32
		return ret
	}
	return *o.Samplerate
}

// GetSamplerateOk returns a tuple with the Samplerate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoStatusEncodingMetadata) GetSamplerateOk() (*int32, bool) {
	if o == nil || o.Samplerate == nil {
		return nil, false
	}
	return o.Samplerate, true
}

// HasSamplerate returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasSamplerate() bool {
	if o != nil && o.Samplerate != nil {
		return true
	}

	return false
}

// SetSamplerate gets a reference to the given int32 and assigns it to the Samplerate field.
func (o *VideoStatusEncodingMetadata) SetSamplerate(v int32) {
	o.Samplerate = &v
}

// GetVideoCodec returns the VideoCodec field value if set, zero value otherwise.
func (o *VideoStatusEncodingMetadata) GetVideoCodec() string {
	if o == nil || o.VideoCodec == nil {
		var ret string
		return ret
	}
	return *o.VideoCodec
}

// GetVideoCodecOk returns a tuple with the VideoCodec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoStatusEncodingMetadata) GetVideoCodecOk() (*string, bool) {
	if o == nil || o.VideoCodec == nil {
		return nil, false
	}
	return o.VideoCodec, true
}

// HasVideoCodec returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasVideoCodec() bool {
	if o != nil && o.VideoCodec != nil {
		return true
	}

	return false
}

// SetVideoCodec gets a reference to the given string and assigns it to the VideoCodec field.
func (o *VideoStatusEncodingMetadata) SetVideoCodec(v string) {
	o.VideoCodec = &v
}

// GetAudioCodec returns the AudioCodec field value if set, zero value otherwise.
func (o *VideoStatusEncodingMetadata) GetAudioCodec() string {
	if o == nil || o.AudioCodec == nil {
		var ret string
		return ret
	}
	return *o.AudioCodec
}

// GetAudioCodecOk returns a tuple with the AudioCodec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoStatusEncodingMetadata) GetAudioCodecOk() (*string, bool) {
	if o == nil || o.AudioCodec == nil {
		return nil, false
	}
	return o.AudioCodec, true
}

// HasAudioCodec returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasAudioCodec() bool {
	if o != nil && o.AudioCodec != nil {
		return true
	}

	return false
}

// SetAudioCodec gets a reference to the given string and assigns it to the AudioCodec field.
func (o *VideoStatusEncodingMetadata) SetAudioCodec(v string) {
	o.AudioCodec = &v
}

// GetAspectRatio returns the AspectRatio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoStatusEncodingMetadata) GetAspectRatio() string {
	if o == nil || o.AspectRatio.Get() == nil {
		var ret string
		return ret
	}
	return *o.AspectRatio.Get()
}

// GetAspectRatioOk returns a tuple with the AspectRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoStatusEncodingMetadata) GetAspectRatioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AspectRatio.Get(), o.AspectRatio.IsSet()
}

// HasAspectRatio returns a boolean if a field has been set.
func (o *VideoStatusEncodingMetadata) HasAspectRatio() bool {
	if o != nil && o.AspectRatio.IsSet() {
		return true
	}

	return false
}

// SetAspectRatio gets a reference to the given NullableString and assigns it to the AspectRatio field.
func (o *VideoStatusEncodingMetadata) SetAspectRatio(v string) {
	o.AspectRatio.Set(&v)
}

// SetAspectRatioNil sets the value for AspectRatio to be an explicit nil
func (o *VideoStatusEncodingMetadata) SetAspectRatioNil() {
	o.AspectRatio.Set(nil)
}

// UnsetAspectRatio ensures that no value is present for AspectRatio, not even an explicit nil
func (o *VideoStatusEncodingMetadata) UnsetAspectRatio() {
	o.AspectRatio.Unset()
}

type NullableVideoStatusEncodingMetadata struct {
	value *VideoStatusEncodingMetadata
	isSet bool
}

func (v NullableVideoStatusEncodingMetadata) Get() *VideoStatusEncodingMetadata {
	return v.value
}

func (v *NullableVideoStatusEncodingMetadata) Set(val *VideoStatusEncodingMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoStatusEncodingMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoStatusEncodingMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoStatusEncodingMetadata(val *VideoStatusEncodingMetadata) *NullableVideoStatusEncodingMetadata {
	return &NullableVideoStatusEncodingMetadata{value: val, isSet: true}
}
