/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// SummaryObject struct for SummaryObject
type SummaryObject struct {
	// The unique identifier of the summary object.
	SummaryId *string `json:"summaryId,omitempty"`
	// Returns the date and time when the summary was created in ATOM date-time format.
	CreatedAt *string `json:"createdAt,omitempty"`
	// Returns the date and time when the summary was last updated in ATOM date-time format.
	UpdatedAt *string `json:"updatedAt,omitempty"`
	// The unique identifier of the video object.
	VideoId *string `json:"videoId,omitempty"`
	// Returns the origin of how the summary was created.  - `api` means that no summary was generated automatically. You can add summary manually using the `PATCH /summaries/{summaryId}/source` endpoint operation. Until this happens, `sourceStatus` returns `missing`. - `auto` means that the API generated the summary automatically.
	Origin *interface{} `json:"origin,omitempty"`
	// Returns the current status of summary generation.  `missing`: the input for a summary is not present. `waiting` : the input video is being processed and a summary will be generated. `failed`: a technical issue prevented summary generation. `completed`: the summary is generated. `unprocessable`: the API rules the source video to be unsuitable for summary generation. An example for this is an input video that has no audio.
	SourceStatus *string `json:"sourceStatus,omitempty"`
}

// NewSummaryObject instantiates a new SummaryObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummaryObject() *SummaryObject {
	this := SummaryObject{}
	return &this
}

// NewSummaryObjectWithDefaults instantiates a new SummaryObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryObjectWithDefaults() *SummaryObject {
	this := SummaryObject{}
	return &this
}

// GetSummaryId returns the SummaryId field value if set, zero value otherwise.
func (o *SummaryObject) GetSummaryId() string {
	if o == nil || o.SummaryId == nil {
		var ret string
		return ret
	}
	return *o.SummaryId
}

// GetSummaryIdOk returns a tuple with the SummaryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryObject) GetSummaryIdOk() (*string, bool) {
	if o == nil || o.SummaryId == nil {
		return nil, false
	}
	return o.SummaryId, true
}

// HasSummaryId returns a boolean if a field has been set.
func (o *SummaryObject) HasSummaryId() bool {
	if o != nil && o.SummaryId != nil {
		return true
	}

	return false
}

// SetSummaryId gets a reference to the given string and assigns it to the SummaryId field.
func (o *SummaryObject) SetSummaryId(v string) {
	o.SummaryId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SummaryObject) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryObject) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SummaryObject) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *SummaryObject) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SummaryObject) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryObject) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SummaryObject) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *SummaryObject) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetVideoId returns the VideoId field value if set, zero value otherwise.
func (o *SummaryObject) GetVideoId() string {
	if o == nil || o.VideoId == nil {
		var ret string
		return ret
	}
	return *o.VideoId
}

// GetVideoIdOk returns a tuple with the VideoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryObject) GetVideoIdOk() (*string, bool) {
	if o == nil || o.VideoId == nil {
		return nil, false
	}
	return o.VideoId, true
}

// HasVideoId returns a boolean if a field has been set.
func (o *SummaryObject) HasVideoId() bool {
	if o != nil && o.VideoId != nil {
		return true
	}

	return false
}

// SetVideoId gets a reference to the given string and assigns it to the VideoId field.
func (o *SummaryObject) SetVideoId(v string) {
	o.VideoId = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SummaryObject) GetOrigin() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SummaryObject) GetOriginOk() (*interface{}, bool) {
	if o == nil || o.Origin == nil {
		return nil, false
	}
	return &o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *SummaryObject) HasOrigin() bool {
	if o != nil && o.Origin != nil {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given interface{} and assigns it to the Origin field.
func (o *SummaryObject) SetOrigin(v interface{}) {
	o.Origin = v
}

// GetSourceStatus returns the SourceStatus field value if set, zero value otherwise.
func (o *SummaryObject) GetSourceStatus() string {
	if o == nil || o.SourceStatus == nil {
		var ret string
		return ret
	}
	return *o.SourceStatus
}

// GetSourceStatusOk returns a tuple with the SourceStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryObject) GetSourceStatusOk() (*string, bool) {
	if o == nil || o.SourceStatus == nil {
		return nil, false
	}
	return o.SourceStatus, true
}

// HasSourceStatus returns a boolean if a field has been set.
func (o *SummaryObject) HasSourceStatus() bool {
	if o != nil && o.SourceStatus != nil {
		return true
	}

	return false
}

// SetSourceStatus gets a reference to the given string and assigns it to the SourceStatus field.
func (o *SummaryObject) SetSourceStatus(v string) {
	o.SourceStatus = &v
}

type NullableSummaryObject struct {
	value *SummaryObject
	isSet bool
}

func (v NullableSummaryObject) Get() *SummaryObject {
	return v.value
}

func (v *NullableSummaryObject) Set(val *SummaryObject) {
	v.value = val
	v.isSet = true
}

func (v NullableSummaryObject) IsSet() bool {
	return v.isSet
}

func (v *NullableSummaryObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummaryObject(val *SummaryObject) *NullableSummaryObject {
	return &NullableSummaryObject{value: val, isSet: true}
}
