/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// RestreamsResponseObject struct for RestreamsResponseObject
type RestreamsResponseObject struct {
	// Returns the name of a restream destination.
	Name *string `json:"name,omitempty"`
	// Returns the server URL of a restream destination.
	ServerUrl *string `json:"serverUrl,omitempty"`
	// Returns the unique key of the live stream that is set up for restreaming.
	StreamKey *string `json:"streamKey,omitempty"`
}

// NewRestreamsResponseObject instantiates a new RestreamsResponseObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestreamsResponseObject() *RestreamsResponseObject {
	this := RestreamsResponseObject{}
	return &this
}

// NewRestreamsResponseObjectWithDefaults instantiates a new RestreamsResponseObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestreamsResponseObjectWithDefaults() *RestreamsResponseObject {
	this := RestreamsResponseObject{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RestreamsResponseObject) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestreamsResponseObject) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RestreamsResponseObject) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RestreamsResponseObject) SetName(v string) {
	o.Name = &v
}

// GetServerUrl returns the ServerUrl field value if set, zero value otherwise.
func (o *RestreamsResponseObject) GetServerUrl() string {
	if o == nil || o.ServerUrl == nil {
		var ret string
		return ret
	}
	return *o.ServerUrl
}

// GetServerUrlOk returns a tuple with the ServerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestreamsResponseObject) GetServerUrlOk() (*string, bool) {
	if o == nil || o.ServerUrl == nil {
		return nil, false
	}
	return o.ServerUrl, true
}

// HasServerUrl returns a boolean if a field has been set.
func (o *RestreamsResponseObject) HasServerUrl() bool {
	if o != nil && o.ServerUrl != nil {
		return true
	}

	return false
}

// SetServerUrl gets a reference to the given string and assigns it to the ServerUrl field.
func (o *RestreamsResponseObject) SetServerUrl(v string) {
	o.ServerUrl = &v
}

// GetStreamKey returns the StreamKey field value if set, zero value otherwise.
func (o *RestreamsResponseObject) GetStreamKey() string {
	if o == nil || o.StreamKey == nil {
		var ret string
		return ret
	}
	return *o.StreamKey
}

// GetStreamKeyOk returns a tuple with the StreamKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestreamsResponseObject) GetStreamKeyOk() (*string, bool) {
	if o == nil || o.StreamKey == nil {
		return nil, false
	}
	return o.StreamKey, true
}

// HasStreamKey returns a boolean if a field has been set.
func (o *RestreamsResponseObject) HasStreamKey() bool {
	if o != nil && o.StreamKey != nil {
		return true
	}

	return false
}

// SetStreamKey gets a reference to the given string and assigns it to the StreamKey field.
func (o *RestreamsResponseObject) SetStreamKey(v string) {
	o.StreamKey = &v
}

type NullableRestreamsResponseObject struct {
	value *RestreamsResponseObject
	isSet bool
}

func (v NullableRestreamsResponseObject) Get() *RestreamsResponseObject {
	return v.value
}

func (v *NullableRestreamsResponseObject) Set(val *RestreamsResponseObject) {
	v.value = val
	v.isSet = true
}

func (v NullableRestreamsResponseObject) IsSet() bool {
	return v.isSet
}

func (v *NullableRestreamsResponseObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestreamsResponseObject(val *RestreamsResponseObject) *NullableRestreamsResponseObject {
	return &NullableRestreamsResponseObject{value: val, isSet: true}
}
