/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// WebhooksCreatePayload struct for WebhooksCreatePayload
type WebhooksCreatePayload struct {
	// A list of the webhooks that you are subscribing to. Currently \"video.encoding.quality.completed\" is the only option. video.encoding.quality.completed - a video encoding quality is ready for the video (for example the 720p quality hls encoding video is ready.)
	Events []string `json:"events"`
	// The the url to which HTTP notifications are sent. It could be any http or https URL.
	Url string `json:"url"`
}

// NewWebhooksCreatePayload instantiates a new WebhooksCreatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhooksCreatePayload(events []string, url string) *WebhooksCreatePayload {
	this := WebhooksCreatePayload{}
	this.Events = events
	this.Url = url
	return &this
}

// NewWebhooksCreatePayloadWithDefaults instantiates a new WebhooksCreatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhooksCreatePayloadWithDefaults() *WebhooksCreatePayload {
	this := WebhooksCreatePayload{}
	return &this
}

// GetEvents returns the Events field value
func (o *WebhooksCreatePayload) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhooksCreatePayload) GetEventsOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Events, true
}

// SetEvents sets field value
func (o *WebhooksCreatePayload) SetEvents(v []string) {
	o.Events = v
}

// GetUrl returns the Url field value
func (o *WebhooksCreatePayload) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhooksCreatePayload) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhooksCreatePayload) SetUrl(v string) {
	o.Url = v
}

type NullableWebhooksCreatePayload struct {
	value *WebhooksCreatePayload
	isSet bool
}

func (v NullableWebhooksCreatePayload) Get() *WebhooksCreatePayload {
	return v.value
}

func (v *NullableWebhooksCreatePayload) Set(val *WebhooksCreatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhooksCreatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhooksCreatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhooksCreatePayload(val *WebhooksCreatePayload) *NullableWebhooksCreatePayload {
	return &NullableWebhooksCreatePayload{value: val, isSet: true}
}
