/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// TooManyRequests struct for TooManyRequests
type TooManyRequests struct {
	// A link to the error documentation.
	Type *string `json:"type,omitempty"`
	// A description of the error that occurred.
	Title *string `json:"title,omitempty"`
	// The HTTP status code.
	Status *int32 `json:"status,omitempty"`
}

// NewTooManyRequests instantiates a new TooManyRequests object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTooManyRequests() *TooManyRequests {
	this := TooManyRequests{}
	return &this
}

// NewTooManyRequestsWithDefaults instantiates a new TooManyRequests object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTooManyRequestsWithDefaults() *TooManyRequests {
	this := TooManyRequests{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TooManyRequests) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TooManyRequests) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TooManyRequests) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TooManyRequests) SetType(v string) {
	o.Type = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *TooManyRequests) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TooManyRequests) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *TooManyRequests) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *TooManyRequests) SetTitle(v string) {
	o.Title = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TooManyRequests) GetStatus() int32 {
	if o == nil || o.Status == nil {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TooManyRequests) GetStatusOk() (*int32, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TooManyRequests) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *TooManyRequests) SetStatus(v int32) {
	o.Status = &v
}

type NullableTooManyRequests struct {
	value *TooManyRequests
	isSet bool
}

func (v NullableTooManyRequests) Get() *TooManyRequests {
	return v.value
}

func (v *NullableTooManyRequests) Set(val *TooManyRequests) {
	v.value = val
	v.isSet = true
}

func (v NullableTooManyRequests) IsSet() bool {
	return v.isSet
}

func (v *NullableTooManyRequests) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTooManyRequests(val *TooManyRequests) *NullableTooManyRequests {
	return &NullableTooManyRequests{value: val, isSet: true}
}
