/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// UploadToken struct for UploadToken
type UploadToken struct {
	// The unique identifier for the token you will use to authenticate an upload.
	Token *string `json:"token,omitempty"`
	// Time-to-live - how long the upload token is valid for.
	Ttl *int32 `json:"ttl,omitempty"`
	// When the token was created, displayed in ISO-8601 format.
	CreatedAt *string `json:"createdAt,omitempty"`
	// When the token expires, displayed in ISO-8601 format.
	ExpiresAt *NullableString `json:"expiresAt,omitempty"`
}

// NewUploadToken instantiates a new UploadToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadToken() *UploadToken {
	this := UploadToken{}
	return &this
}

// NewUploadTokenWithDefaults instantiates a new UploadToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadTokenWithDefaults() *UploadToken {
	this := UploadToken{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *UploadToken) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadToken) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *UploadToken) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *UploadToken) SetToken(v string) {
	o.Token = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *UploadToken) GetTtl() int32 {
	if o == nil || o.Ttl == nil {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadToken) GetTtlOk() (*int32, bool) {
	if o == nil || o.Ttl == nil {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *UploadToken) HasTtl() bool {
	if o != nil && o.Ttl != nil {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *UploadToken) SetTtl(v int32) {
	o.Ttl = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UploadToken) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadToken) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UploadToken) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *UploadToken) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadToken) GetExpiresAt() string {
	if o == nil || o.ExpiresAt.Get() == nil {
		var ret string
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadToken) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *UploadToken) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableString and assigns it to the ExpiresAt field.
func (o *UploadToken) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}

// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *UploadToken) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *UploadToken) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

type NullableUploadToken struct {
	value *UploadToken
	isSet bool
}

func (v NullableUploadToken) Get() *UploadToken {
	return v.value
}

func (v *NullableUploadToken) Set(val *UploadToken) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadToken) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadToken(val *UploadToken) *NullableUploadToken {
	return &NullableUploadToken{value: val, isSet: true}
}
