/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// CaptionsListResponse struct for CaptionsListResponse
type CaptionsListResponse struct {
	Data       *[]Subtitle `json:"data,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewCaptionsListResponse instantiates a new CaptionsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptionsListResponse() *CaptionsListResponse {
	this := CaptionsListResponse{}
	return &this
}

// NewCaptionsListResponseWithDefaults instantiates a new CaptionsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptionsListResponseWithDefaults() *CaptionsListResponse {
	this := CaptionsListResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CaptionsListResponse) GetData() []Subtitle {
	if o == nil || o.Data == nil {
		var ret []Subtitle
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptionsListResponse) GetDataOk() (*[]Subtitle, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CaptionsListResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []Subtitle and assigns it to the Data field.
func (o *CaptionsListResponse) SetData(v []Subtitle) {
	o.Data = &v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *CaptionsListResponse) GetPagination() Pagination {
	if o == nil || o.Pagination == nil {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptionsListResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *CaptionsListResponse) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *CaptionsListResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

type NullableCaptionsListResponse struct {
	value *CaptionsListResponse
	isSet bool
}

func (v NullableCaptionsListResponse) Get() *CaptionsListResponse {
	return v.value
}

func (v *NullableCaptionsListResponse) Set(val *CaptionsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptionsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptionsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptionsListResponse(val *CaptionsListResponse) *NullableCaptionsListResponse {
	return &NullableCaptionsListResponse{value: val, isSet: true}
}
