/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// AnalyticsPlaysResponse struct for AnalyticsPlaysResponse
type AnalyticsPlaysResponse struct {
	Data       []AnalyticsData `json:"data"`
	Pagination Pagination      `json:"pagination"`
}

// NewAnalyticsPlaysResponse instantiates a new AnalyticsPlaysResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsPlaysResponse(data []AnalyticsData, pagination Pagination) *AnalyticsPlaysResponse {
	this := AnalyticsPlaysResponse{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewAnalyticsPlaysResponseWithDefaults instantiates a new AnalyticsPlaysResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsPlaysResponseWithDefaults() *AnalyticsPlaysResponse {
	this := AnalyticsPlaysResponse{}
	return &this
}

// GetData returns the Data field value
func (o *AnalyticsPlaysResponse) GetData() []AnalyticsData {
	if o == nil {
		var ret []AnalyticsData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AnalyticsPlaysResponse) GetDataOk() (*[]AnalyticsData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AnalyticsPlaysResponse) SetData(v []AnalyticsData) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *AnalyticsPlaysResponse) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *AnalyticsPlaysResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *AnalyticsPlaysResponse) SetPagination(v Pagination) {
	o.Pagination = v
}

type NullableAnalyticsPlaysResponse struct {
	value *AnalyticsPlaysResponse
	isSet bool
}

func (v NullableAnalyticsPlaysResponse) Get() *AnalyticsPlaysResponse {
	return v.value
}

func (v *NullableAnalyticsPlaysResponse) Set(val *AnalyticsPlaysResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsPlaysResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsPlaysResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsPlaysResponse(val *AnalyticsPlaysResponse) *NullableAnalyticsPlaysResponse {
	return &NullableAnalyticsPlaysResponse{value: val, isSet: true}
}
