/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// Watermark struct for Watermark
type Watermark struct {
	// The unique identifier of the watermark.
	WatermarkId *string `json:"watermarkId,omitempty"`
	// When the watermark was created, presented in ISO-8601 format.
	CreatedAt *string `json:"createdAt,omitempty"`
}

// NewWatermark instantiates a new Watermark object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWatermark() *Watermark {
	this := Watermark{}
	return &this
}

// NewWatermarkWithDefaults instantiates a new Watermark object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWatermarkWithDefaults() *Watermark {
	this := Watermark{}
	return &this
}

// GetWatermarkId returns the WatermarkId field value if set, zero value otherwise.
func (o *Watermark) GetWatermarkId() string {
	if o == nil || o.WatermarkId == nil {
		var ret string
		return ret
	}
	return *o.WatermarkId
}

// GetWatermarkIdOk returns a tuple with the WatermarkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetWatermarkIdOk() (*string, bool) {
	if o == nil || o.WatermarkId == nil {
		return nil, false
	}
	return o.WatermarkId, true
}

// HasWatermarkId returns a boolean if a field has been set.
func (o *Watermark) HasWatermarkId() bool {
	if o != nil && o.WatermarkId != nil {
		return true
	}

	return false
}

// SetWatermarkId gets a reference to the given string and assigns it to the WatermarkId field.
func (o *Watermark) SetWatermarkId(v string) {
	o.WatermarkId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Watermark) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Watermark) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *Watermark) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

type NullableWatermark struct {
	value *Watermark
	isSet bool
}

func (v NullableWatermark) Get() *Watermark {
	return v.value
}

func (v *NullableWatermark) Set(val *Watermark) {
	v.value = val
	v.isSet = true
}

func (v NullableWatermark) IsSet() bool {
	return v.isSet
}

func (v *NullableWatermark) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWatermark(val *Watermark) *NullableWatermark {
	return &NullableWatermark{value: val, isSet: true}
}
