/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// AnalyticsAggregatedMetricsResponse struct for AnalyticsAggregatedMetricsResponse
type AnalyticsAggregatedMetricsResponse struct {
	Context AnalyticsAggregatedMetricsResponseContext `json:"context"`
	Data    float32                                   `json:"data"`
}

// NewAnalyticsAggregatedMetricsResponse instantiates a new AnalyticsAggregatedMetricsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsAggregatedMetricsResponse(context AnalyticsAggregatedMetricsResponseContext, data float32) *AnalyticsAggregatedMetricsResponse {
	this := AnalyticsAggregatedMetricsResponse{}
	this.Context = context
	this.Data = data
	return &this
}

// NewAnalyticsAggregatedMetricsResponseWithDefaults instantiates a new AnalyticsAggregatedMetricsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsAggregatedMetricsResponseWithDefaults() *AnalyticsAggregatedMetricsResponse {
	this := AnalyticsAggregatedMetricsResponse{}
	return &this
}

// GetContext returns the Context field value
func (o *AnalyticsAggregatedMetricsResponse) GetContext() AnalyticsAggregatedMetricsResponseContext {
	if o == nil {
		var ret AnalyticsAggregatedMetricsResponseContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *AnalyticsAggregatedMetricsResponse) GetContextOk() (*AnalyticsAggregatedMetricsResponseContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *AnalyticsAggregatedMetricsResponse) SetContext(v AnalyticsAggregatedMetricsResponseContext) {
	o.Context = v
}

// GetData returns the Data field value
func (o *AnalyticsAggregatedMetricsResponse) GetData() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AnalyticsAggregatedMetricsResponse) GetDataOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AnalyticsAggregatedMetricsResponse) SetData(v float32) {
	o.Data = v
}

type NullableAnalyticsAggregatedMetricsResponse struct {
	value *AnalyticsAggregatedMetricsResponse
	isSet bool
}

func (v NullableAnalyticsAggregatedMetricsResponse) Get() *AnalyticsAggregatedMetricsResponse {
	return v.value
}

func (v *NullableAnalyticsAggregatedMetricsResponse) Set(val *AnalyticsAggregatedMetricsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsAggregatedMetricsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsAggregatedMetricsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsAggregatedMetricsResponse(val *AnalyticsAggregatedMetricsResponse) *NullableAnalyticsAggregatedMetricsResponse {
	return &NullableAnalyticsAggregatedMetricsResponse{value: val, isSet: true}
}
