/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// WebhooksCreationPayload struct for WebhooksCreationPayload
type WebhooksCreationPayload struct {
	// A list of the webhooks that you are subscribing to. Currently \"video.encoding.quality.completed\" is the only option. video.encoding.quality.completed - a video encoding quality is ready for the video (for example the 720p quality hls encoding video is ready.)
	Events []string `json:"events"`
	// The the url to which HTTP notifications are sent. It could be any http or https URL.
	Url string `json:"url"`
}

// NewWebhooksCreationPayload instantiates a new WebhooksCreationPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhooksCreationPayload(events []string, url string) *WebhooksCreationPayload {
	this := WebhooksCreationPayload{}
	this.Events = events
	this.Url = url
	return &this
}

// NewWebhooksCreationPayloadWithDefaults instantiates a new WebhooksCreationPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhooksCreationPayloadWithDefaults() *WebhooksCreationPayload {
	this := WebhooksCreationPayload{}
	return &this
}

// GetEvents returns the Events field value
func (o *WebhooksCreationPayload) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhooksCreationPayload) GetEventsOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Events, true
}

// SetEvents sets field value
func (o *WebhooksCreationPayload) SetEvents(v []string) {
	o.Events = v
}

// GetUrl returns the Url field value
func (o *WebhooksCreationPayload) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhooksCreationPayload) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhooksCreationPayload) SetUrl(v string) {
	o.Url = v
}

type NullableWebhooksCreationPayload struct {
	value *WebhooksCreationPayload
	isSet bool
}

func (v NullableWebhooksCreationPayload) Get() *WebhooksCreationPayload {
	return v.value
}

func (v *NullableWebhooksCreationPayload) Set(val *WebhooksCreationPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhooksCreationPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhooksCreationPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhooksCreationPayload(val *WebhooksCreationPayload) *NullableWebhooksCreationPayload {
	return &NullableWebhooksCreationPayload{value: val, isSet: true}
}
