/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// ChaptersListResponse struct for ChaptersListResponse
type ChaptersListResponse struct {
	Data       []Chapter  `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// NewChaptersListResponse instantiates a new ChaptersListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChaptersListResponse(data []Chapter, pagination Pagination) *ChaptersListResponse {
	this := ChaptersListResponse{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewChaptersListResponseWithDefaults instantiates a new ChaptersListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChaptersListResponseWithDefaults() *ChaptersListResponse {
	this := ChaptersListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ChaptersListResponse) GetData() []Chapter {
	if o == nil {
		var ret []Chapter
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ChaptersListResponse) GetDataOk() (*[]Chapter, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ChaptersListResponse) SetData(v []Chapter) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *ChaptersListResponse) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ChaptersListResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ChaptersListResponse) SetPagination(v Pagination) {
	o.Pagination = v
}

type NullableChaptersListResponse struct {
	value *ChaptersListResponse
	isSet bool
}

func (v NullableChaptersListResponse) Get() *ChaptersListResponse {
	return v.value
}

func (v *NullableChaptersListResponse) Set(val *ChaptersListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChaptersListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChaptersListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChaptersListResponse(val *ChaptersListResponse) *NullableChaptersListResponse {
	return &NullableChaptersListResponse{value: val, isSet: true}
}
