/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// LiveStreamListResponse struct for LiveStreamListResponse
type LiveStreamListResponse struct {
	Data       []LiveStream `json:"data"`
	Pagination Pagination   `json:"pagination"`
}

// NewLiveStreamListResponse instantiates a new LiveStreamListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiveStreamListResponse(data []LiveStream, pagination Pagination) *LiveStreamListResponse {
	this := LiveStreamListResponse{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewLiveStreamListResponseWithDefaults instantiates a new LiveStreamListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiveStreamListResponseWithDefaults() *LiveStreamListResponse {
	this := LiveStreamListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *LiveStreamListResponse) GetData() []LiveStream {
	if o == nil {
		var ret []LiveStream
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *LiveStreamListResponse) GetDataOk() (*[]LiveStream, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *LiveStreamListResponse) SetData(v []LiveStream) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *LiveStreamListResponse) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *LiveStreamListResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *LiveStreamListResponse) SetPagination(v Pagination) {
	o.Pagination = v
}

type NullableLiveStreamListResponse struct {
	value *LiveStreamListResponse
	isSet bool
}

func (v NullableLiveStreamListResponse) Get() *LiveStreamListResponse {
	return v.value
}

func (v *NullableLiveStreamListResponse) Set(val *LiveStreamListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveStreamListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveStreamListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveStreamListResponse(val *LiveStreamListResponse) *NullableLiveStreamListResponse {
	return &NullableLiveStreamListResponse{value: val, isSet: true}
}
