/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// VideoThumbnailPickPayload struct for VideoThumbnailPickPayload
type VideoThumbnailPickPayload struct {
	// Frame in video to be used as a placeholder before the video plays.  Example: '\"00:01:00.000\" for 1 minute into the video.' Valid Patterns:  \"hh:mm:ss.ms\" \"hh:mm:ss:frameNumber\" \"124\" (integer value is reported as seconds)  If selection is out of range, \"00:00:00.00\" will be chosen.
	Timecode string `json:"timecode"`
}

// NewVideoThumbnailPickPayload instantiates a new VideoThumbnailPickPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoThumbnailPickPayload(timecode string) *VideoThumbnailPickPayload {
	this := VideoThumbnailPickPayload{}
	this.Timecode = timecode
	return &this
}

// NewVideoThumbnailPickPayloadWithDefaults instantiates a new VideoThumbnailPickPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoThumbnailPickPayloadWithDefaults() *VideoThumbnailPickPayload {
	this := VideoThumbnailPickPayload{}
	return &this
}

// GetTimecode returns the Timecode field value
func (o *VideoThumbnailPickPayload) GetTimecode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timecode
}

// GetTimecodeOk returns a tuple with the Timecode field value
// and a boolean to check if the value has been set.
func (o *VideoThumbnailPickPayload) GetTimecodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timecode, true
}

// SetTimecode sets field value
func (o *VideoThumbnailPickPayload) SetTimecode(v string) {
	o.Timecode = v
}

type NullableVideoThumbnailPickPayload struct {
	value *VideoThumbnailPickPayload
	isSet bool
}

func (v NullableVideoThumbnailPickPayload) Get() *VideoThumbnailPickPayload {
	return v.value
}

func (v *NullableVideoThumbnailPickPayload) Set(val *VideoThumbnailPickPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoThumbnailPickPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoThumbnailPickPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoThumbnailPickPayload(val *VideoThumbnailPickPayload) *NullableVideoThumbnailPickPayload {
	return &NullableVideoThumbnailPickPayload{value: val, isSet: true}
}
