/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// RawStatisticsListLiveStreamAnalyticsResponse struct for RawStatisticsListLiveStreamAnalyticsResponse
type RawStatisticsListLiveStreamAnalyticsResponse struct {
	Data       *[]LiveStreamSession `json:"data,omitempty"`
	Pagination *Pagination          `json:"pagination,omitempty"`
}

// NewRawStatisticsListLiveStreamAnalyticsResponse instantiates a new RawStatisticsListLiveStreamAnalyticsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRawStatisticsListLiveStreamAnalyticsResponse() *RawStatisticsListLiveStreamAnalyticsResponse {
	this := RawStatisticsListLiveStreamAnalyticsResponse{}
	return &this
}

// NewRawStatisticsListLiveStreamAnalyticsResponseWithDefaults instantiates a new RawStatisticsListLiveStreamAnalyticsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRawStatisticsListLiveStreamAnalyticsResponseWithDefaults() *RawStatisticsListLiveStreamAnalyticsResponse {
	this := RawStatisticsListLiveStreamAnalyticsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RawStatisticsListLiveStreamAnalyticsResponse) GetData() []LiveStreamSession {
	if o == nil || o.Data == nil {
		var ret []LiveStreamSession
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawStatisticsListLiveStreamAnalyticsResponse) GetDataOk() (*[]LiveStreamSession, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RawStatisticsListLiveStreamAnalyticsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []LiveStreamSession and assigns it to the Data field.
func (o *RawStatisticsListLiveStreamAnalyticsResponse) SetData(v []LiveStreamSession) {
	o.Data = &v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *RawStatisticsListLiveStreamAnalyticsResponse) GetPagination() Pagination {
	if o == nil || o.Pagination == nil {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawStatisticsListLiveStreamAnalyticsResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *RawStatisticsListLiveStreamAnalyticsResponse) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *RawStatisticsListLiveStreamAnalyticsResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

type NullableRawStatisticsListLiveStreamAnalyticsResponse struct {
	value *RawStatisticsListLiveStreamAnalyticsResponse
	isSet bool
}

func (v NullableRawStatisticsListLiveStreamAnalyticsResponse) Get() *RawStatisticsListLiveStreamAnalyticsResponse {
	return v.value
}

func (v *NullableRawStatisticsListLiveStreamAnalyticsResponse) Set(val *RawStatisticsListLiveStreamAnalyticsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRawStatisticsListLiveStreamAnalyticsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRawStatisticsListLiveStreamAnalyticsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRawStatisticsListLiveStreamAnalyticsResponse(val *RawStatisticsListLiveStreamAnalyticsResponse) *NullableRawStatisticsListLiveStreamAnalyticsResponse {
	return &NullableRawStatisticsListLiveStreamAnalyticsResponse{value: val, isSet: true}
}
