/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// LiveStreamSessionSession struct for LiveStreamSessionSession
type LiveStreamSessionSession struct {
	// A unique identifier for your session. You can use this to track what happens during a specific session.
	SessionId *string `json:"sessionId,omitempty"`
	// When the session started, with the date and time presented in ISO-8601 format.
	LoadedAt *string `json:"loadedAt,omitempty"`
	// When the session ended, with the date and time presented in ISO-8601 format.
	EndedAt *string `json:"endedAt,omitempty"`
}

// NewLiveStreamSessionSession instantiates a new LiveStreamSessionSession object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiveStreamSessionSession() *LiveStreamSessionSession {
	this := LiveStreamSessionSession{}
	return &this
}

// NewLiveStreamSessionSessionWithDefaults instantiates a new LiveStreamSessionSession object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiveStreamSessionSessionWithDefaults() *LiveStreamSessionSession {
	this := LiveStreamSessionSession{}
	return &this
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *LiveStreamSessionSession) GetSessionId() string {
	if o == nil || o.SessionId == nil {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveStreamSessionSession) GetSessionIdOk() (*string, bool) {
	if o == nil || o.SessionId == nil {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *LiveStreamSessionSession) HasSessionId() bool {
	if o != nil && o.SessionId != nil {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *LiveStreamSessionSession) SetSessionId(v string) {
	o.SessionId = &v
}

// GetLoadedAt returns the LoadedAt field value if set, zero value otherwise.
func (o *LiveStreamSessionSession) GetLoadedAt() string {
	if o == nil || o.LoadedAt == nil {
		var ret string
		return ret
	}
	return *o.LoadedAt
}

// GetLoadedAtOk returns a tuple with the LoadedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveStreamSessionSession) GetLoadedAtOk() (*string, bool) {
	if o == nil || o.LoadedAt == nil {
		return nil, false
	}
	return o.LoadedAt, true
}

// HasLoadedAt returns a boolean if a field has been set.
func (o *LiveStreamSessionSession) HasLoadedAt() bool {
	if o != nil && o.LoadedAt != nil {
		return true
	}

	return false
}

// SetLoadedAt gets a reference to the given string and assigns it to the LoadedAt field.
func (o *LiveStreamSessionSession) SetLoadedAt(v string) {
	o.LoadedAt = &v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *LiveStreamSessionSession) GetEndedAt() string {
	if o == nil || o.EndedAt == nil {
		var ret string
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveStreamSessionSession) GetEndedAtOk() (*string, bool) {
	if o == nil || o.EndedAt == nil {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *LiveStreamSessionSession) HasEndedAt() bool {
	if o != nil && o.EndedAt != nil {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given string and assigns it to the EndedAt field.
func (o *LiveStreamSessionSession) SetEndedAt(v string) {
	o.EndedAt = &v
}

type NullableLiveStreamSessionSession struct {
	value *LiveStreamSessionSession
	isSet bool
}

func (v NullableLiveStreamSessionSession) Get() *LiveStreamSessionSession {
	return v.value
}

func (v *NullableLiveStreamSessionSession) Set(val *LiveStreamSessionSession) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveStreamSessionSession) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveStreamSessionSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveStreamSessionSession(val *LiveStreamSessionSession) *NullableLiveStreamSessionSession {
	return &NullableLiveStreamSessionSession{value: val, isSet: true}
}
