/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// PlayerAssets struct for PlayerAssets
type PlayerAssets struct {
	// The name of the file containing the logo you want to use.
	Logo *string `json:"logo,omitempty"`
	// The path to the file containing your logo.
	Link *string `json:"link,omitempty"`
}

// NewPlayerAssets instantiates a new PlayerAssets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerAssets() *PlayerAssets {
	this := PlayerAssets{}
	return &this
}

// NewPlayerAssetsWithDefaults instantiates a new PlayerAssets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerAssetsWithDefaults() *PlayerAssets {
	this := PlayerAssets{}
	return &this
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *PlayerAssets) GetLogo() string {
	if o == nil || o.Logo == nil {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAssets) GetLogoOk() (*string, bool) {
	if o == nil || o.Logo == nil {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *PlayerAssets) HasLogo() bool {
	if o != nil && o.Logo != nil {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *PlayerAssets) SetLogo(v string) {
	o.Logo = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *PlayerAssets) GetLink() string {
	if o == nil || o.Link == nil {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerAssets) GetLinkOk() (*string, bool) {
	if o == nil || o.Link == nil {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *PlayerAssets) HasLink() bool {
	if o != nil && o.Link != nil {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *PlayerAssets) SetLink(v string) {
	o.Link = &v
}

type NullablePlayerAssets struct {
	value *PlayerAssets
	isSet bool
}

func (v NullablePlayerAssets) Get() *PlayerAssets {
	return v.value
}

func (v *NullablePlayerAssets) Set(val *PlayerAssets) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerAssets) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerAssets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerAssets(val *PlayerAssets) *NullablePlayerAssets {
	return &NullablePlayerAssets{value: val, isSet: true}
}
