/*
 * api.video
 *
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apivideosdk

import (
//"encoding/json"
)

// AnalyticsPlays400Error struct for AnalyticsPlays400Error
type AnalyticsPlays400Error struct {
	// A link to the error documentation.
	Type *string `json:"type,omitempty"`
	// A description of the error that occurred.
	Title *string `json:"title,omitempty"`
	// The HTTP status code.
	Status *int32 `json:"status,omitempty"`
	// A solution for the error.
	Detail *string `json:"detail,omitempty"`
	// The name of the parameter that caused the error.
	Name *string `json:"name,omitempty"`
}

// NewAnalyticsPlays400Error instantiates a new AnalyticsPlays400Error object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsPlays400Error() *AnalyticsPlays400Error {
	this := AnalyticsPlays400Error{}
	return &this
}

// NewAnalyticsPlays400ErrorWithDefaults instantiates a new AnalyticsPlays400Error object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsPlays400ErrorWithDefaults() *AnalyticsPlays400Error {
	this := AnalyticsPlays400Error{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AnalyticsPlays400Error) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsPlays400Error) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AnalyticsPlays400Error) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AnalyticsPlays400Error) SetType(v string) {
	o.Type = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AnalyticsPlays400Error) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsPlays400Error) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AnalyticsPlays400Error) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AnalyticsPlays400Error) SetTitle(v string) {
	o.Title = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AnalyticsPlays400Error) GetStatus() int32 {
	if o == nil || o.Status == nil {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsPlays400Error) GetStatusOk() (*int32, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AnalyticsPlays400Error) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *AnalyticsPlays400Error) SetStatus(v int32) {
	o.Status = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *AnalyticsPlays400Error) GetDetail() string {
	if o == nil || o.Detail == nil {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsPlays400Error) GetDetailOk() (*string, bool) {
	if o == nil || o.Detail == nil {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *AnalyticsPlays400Error) HasDetail() bool {
	if o != nil && o.Detail != nil {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *AnalyticsPlays400Error) SetDetail(v string) {
	o.Detail = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AnalyticsPlays400Error) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsPlays400Error) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AnalyticsPlays400Error) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AnalyticsPlays400Error) SetName(v string) {
	o.Name = &v
}

type NullableAnalyticsPlays400Error struct {
	value *AnalyticsPlays400Error
	isSet bool
}

func (v NullableAnalyticsPlays400Error) Get() *AnalyticsPlays400Error {
	return v.value
}

func (v *NullableAnalyticsPlays400Error) Set(val *AnalyticsPlays400Error) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsPlays400Error) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsPlays400Error) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsPlays400Error(val *AnalyticsPlays400Error) *NullableAnalyticsPlays400Error {
	return &NullableAnalyticsPlays400Error{value: val, isSet: true}
}
