name: Run unit tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URI: https://ws.api.video